<a href="https://colab.research.google.com/github/SPECTRE200-4/DATA-VISUALIZATION/blob/main/SDS2206/CAT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import statistics as stats


# E_commerce as dictionary
e_commerce = {
    "ID":["E001", "E002", "E003", "E004", "E005", "E006"],
    "Month":["Jan","Feb","Mar","Apr","May","Jun"],
    "UnitSold":[200, 230, 210, 250, 220, 260],
    "Promotions":["No", "Yes", "No", "Yes", "No", "Yes"],
    "Revenue":[4000, 4600, 4200, 5000, 4400, 5200],
    "Customers":[120, 140, 130, 150, 135, 160]
}

df = pd.DataFrame(e_commerce)
print(df)

df["Revenue_Growth"] = df["Revenue"].pct_change() * 100
print(df)
print(df["Revenue"].describe())
print("Measure of dispersion:")
print("Range of Revenue:", df["Revenue"].max() - df["Revenue"].min())
print("Variance of Revenue:", df["Revenue"].var())
print("Standard Deviation of Revenue:", df["Revenue"].std())

print(df['Customers'].describe())
print("Measure of dispersion:")
print("Range of Customers:", df["Customers"].max() - df["Customers"].min())
print("Variance of Customers:", df["Customers"].var())
print("Standard Deviation of Customers:", df["Customers"].std())

     ID Month  UnitSold Promotions  Revenue  Customers
0  E001   Jan       200         No     4000        120
1  E002   Feb       230        Yes     4600        140
2  E003   Mar       210         No     4200        130
3  E004   Apr       250        Yes     5000        150
4  E005   May       220         No     4400        135
5  E006   Jun       260        Yes     5200        160
     ID Month  UnitSold Promotions  Revenue  Customers  Revenue_Growth
0  E001   Jan       200         No     4000        120             NaN
1  E002   Feb       230        Yes     4600        140       15.000000
2  E003   Mar       210         No     4200        130       -8.695652
3  E004   Apr       250        Yes     5000        150       19.047619
4  E005   May       220         No     4400        135      -12.000000
5  E006   Jun       260        Yes     5200        160       18.181818
count       6.000000
mean     4566.666667
std       463.321343
min      4000.000000
25%      4250.000000
50%      4500.000000
75%      4900.000000
max      5200.000000
Name: Revenue, dtype: float64
Measure of dispersion:
Range of Revenue: 1200
Variance of Revenue: 214666.66666666666
Standard Deviation of Revenue: 463.3213427705081
count      6.000000
mean     139.166667
std       14.288690
min      120.000000
25%      131.250000
50%      137.500000
75%      147.500000
max      160.000000
Name: Customers, dtype: float64
Measure of dispersion:
Range of Customers: 40
Variance of Customers: 204.16666666666669
Standard Deviation of Customers: 14.288690166235206

In [40]:
import pandas as pd
import sklearn as sklearn


# Energy Consumption as a dictionary
energy_consumption = {
    "ID":["EN001", "EN002", "EN003", "EN004", "EN005", "EN006"],
    "Temp":[24, 28, 22, 27, 23, 26],
    "Humidity":[60, 55, 70, 58, 72, 62],
    "EnergyUsage":[350, 400, 300, 420, 320, 380],
    "WindSpeed":[10, 12, 8, 11, 7, 9],
    "Location":["Residential", "Residential", "Industrial", "Residential", "Industrial", "Residential"]
}

df = pd.DataFrame(energy_consumption)
df.describe()

from sklearn.preprocessing import StandardScaler

# Select only numerical columns for scaling
numerical_cols = ['Temp', 'Humidity', 'EnergyUsage', 'WindSpeed']
df_numerical = df[numerical_cols]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_numerical)
scaled_df = pd.DataFrame(scaled_data, columns=numerical_cols)
df["LocationCode"] = df["Location"].map({"Industrial":0, "Residential":1})
print(scaled_df.head())
print(df.head())

#Statistical Aggragation by Location

print('Descriptive Statistics by Location')

for location, group in df.groupby('Location'):
    print(f'\nLocation: {location}')
    display(group.describe())

      Temp  Humidity  EnergyUsage  WindSpeed
0 -0.46291 -0.458790    -0.273931    0.29277
1  1.38873 -1.268419     0.900060    1.46385
2 -1.38873  1.160468    -1.447922   -0.87831
3  0.92582 -0.782641     1.369656    0.87831
4 -0.92582  1.484320    -0.978326   -1.46385
      ID  Temp  Humidity  EnergyUsage  WindSpeed     Location  LocationCode
0  EN001    24        60          350         10  Residential             1
1  EN002    28        55          400         12  Residential             1
2  EN003    22        70          300          8   Industrial             0
3  EN004    27        58          420         11  Residential             1
4  EN005    23        72          320          7   Industrial             0
      ID  Temp  Humidity  EnergyUsage  WindSpeed     Location  LocationCode
0  EN001    24        60          350         10  Residential             1
1  EN002    28        55          400         12  Residential             1
2  EN003    22        70          300          8   Industrial             0
3  EN004    27        58          420         11  Residential             1
4  EN005    23        72          320          7   Industrial             0
5  EN006    26        62          380          9  Residential             1
Descriptive Statistics by Location

Location: Industrial

            Temp   Humidity  EnergyUsage  WindSpeed  LocationCode
count   2.000000   2.000000     2.000000   2.000000           2.0
mean   22.500000  71.000000   310.000000   7.500000           0.0
std     0.707107   1.414214    14.142136   0.707107           0.0
min    22.000000  70.000000   300.000000   7.000000           0.0
25%    22.250000  70.500000   305.000000   7.250000           0.0
50%    22.500000  71.000000   310.000000   7.500000           0.0
75%    22.750000  71.500000   315.000000   7.750000           0.0
max    23.000000  72.000000   320.000000   8.000000           0.0

Location: Residential

            Temp   Humidity  EnergyUsage  WindSpeed  LocationCode
count   4.000000   4.000000     4.000000   4.000000           4.0
mean   26.250000  58.750000   387.500000  10.500000           1.0
std     1.707825   2.986079    29.860788   1.290994           0.0
min    24.000000  55.000000   350.000000   9.000000           1.0
25%    25.500000  57.250000   372.500000   9.750000           1.0
50%    26.500000  59.000000   390.000000  10.500000           1.0
75%    27.250000  60.500000   405.000000  11.250000           1.0
max    28.000000  62.000000   420.000000  12.000000           1.0

In [37]:
# Import packages
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


# Load the data
df = pd.DataFrame(energy_consumption)

# Create feature and target arrays
X = df[['Temp', 'Humidity', 'WindSpeed']]
y = df['EnergyUsage']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X, y)

# predicting on the X_test data set
print("Predictions:")
print(model.predict(X_test))

# summary of the model
print('model intercept :', model.intercept_)
print('model coefficients : ', model.coef_)
print('Model score : ', model.score(X_test, y_test))

Predictions:
[349.62543992 415.85218703]
model intercept : 191.4906988436403
model coefficients :  [16.52589241 -2.81297134 -6.97083962]
Model score :  0.7988542969236784